name: Update Wine Catalog

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update-catalog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: npm install
      - run: node scripts/sync-catalog.js
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/lib/boirCatalog.js
          git commit -m "🌍 Synchro Internationale" || exit 0
          git pull --rebase origin main
          git push origin main
